version: 1.9.0-{build}

os: Visual Studio 2022

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

branches:
  only:
  - main

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

init:
- cmd: git config --global core.autocrlf true

install:
- cmd: IF DEFINED HFPass nuget sources add -Name ExtHf -Source %HFFeedUrl% -UserName %HFUser% -Password %HFPass%

build_script:
- cmd: IF DEFINED HFPass dotnet build /p:ContinuousIntegrationBuild=true -c ReleasePro Hangfire.Tags.sln
- cmd: IF NOT DEFINED HFPass dotnet build /p:ContinuousIntegrationBuild=true -c Release Hangfire.Tags.sln

after_build:
- cmd: IF DEFINED HFPass dotnet pack /p:ContinuousIntegrationBuild=true -c ReleasePro -o artifacts Hangfire.Tags.sln
- cmd: IF NOT DEFINED HFPass dotnet pack /p:ContinuousIntegrationBuild=true -c Release -o artifacts Hangfire.Tags.sln

test_script:
- cmd: dotnet test tests/FaceIT.Hangfire.Tags.Tests/FaceIT.Hangfire.Tags.Tests.csproj
- cmd: dotnet test tests/FaceIT.Hangfire.Tags.PostgreSql.Tests/FaceIT.Hangfire.Tags.PostgreSql.Tests.csproj
- cmd: dotnet test tests/FaceIT.Hangfire.Tags.MySql.Tests/FaceIT.Hangfire.Tags.MySql.Tests.csproj

artifacts:
- path: 'artifacts/**/*.*nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: Sv/gzOW796jlrE9VF/b/Lv0zKSCe2H3eXS1aFyl48p9jYrARL7S9Nlr5wioZ0kF5
  skip_symbols: false
  on:
    branch: 
    - main
