#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Tags.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
    using Hangfire.Tags.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class TagsSearchPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
  
    Layout = new LayoutPage("Tags");

    int.TryParse(Query("from"), out var from);
    int.TryParse(Query("count"), out var perPage);

    var tag = Query("tag");

    var tagStorage = new TagsStorage(Storage);

    var monitor = tagStorage.GetMonitoringApi();


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 22 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">Tags</h" +
"1>\r\n        \r\n        <!-- Add search box here -->\r\n\r\n");


            
            #line 29 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
          
            if (string.IsNullOrEmpty(tag))
            {
                // Show a page with all tags
                var allTags = tagStorage.GetAllTags();


            
            #line default
            #line hidden
WriteLiteral("                <div class=\"tags\">\r\n");


            
            #line 36 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                     foreach (var t in allTags)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <span class=\"label label-info\">");


            
            #line 38 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                                  Write(t);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 39 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n");


            
            #line 41 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
            }
            else
            {
                // Show a page with a list of matching jobs

                var pager = new Pager(from, perPage, monitor.GetJobCount(tag));
                var matchingJobs = monitor.GetMatchingJobs(tag, pager.FromRecord, pager.RecordsPerPage);

                if (pager.TotalPageCount == 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                     <div class=\"alert alert-info\">\r\n                         ");


            
            #line 52 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                    Write(Strings.SucceededJobsPage_NoJobs);

            
            #line default
            #line hidden
WriteLiteral("\r\n                     </div>\r\n");


            
            #line 54 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"js-jobs-list\">\r\n                        <div clas" +
"s=\"btn-toolbar btn-toolbar-top\">\r\n                            <button class=\"js-" +
"jobs-list-command btn btn-sm btn-primary\"\r\n                                    d" +
"ata-url=\"");


            
            #line 60 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                         Write(Url.To("/jobs/enqueued/requeue"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                                    data-loading-text=\"");


            
            #line 61 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                                  Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                                    disabled=\"disabled\">\r\n                    " +
"            <span class=\"glyphicon glyphicon-repeat\"></span>\r\n                  " +
"              ");


            
            #line 64 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                           Write(Strings.Common_RequeueJobs);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </button>\r\n\r\n                            ");


            
            #line 67 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                       Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral(@"
                        </div>

                        <div class=""table-responsive"">
                            <table class=""table"">
                                <thead>
                                <tr>
                                    <th class=""min-width"">
                                        <input type=""checkbox"" class=""js-jobs-list-select-all""/>
                                    </th>
                                    <th class=""min-width"">");


            
            #line 77 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                                     Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                    <th>");


            
            #line 78 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                   Write(Strings.Common_Job);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                    <th class=\"align-right\">");


            
            #line 79 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                                       Write(Strings.Common_State);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                </tr>\r\n                                </t" +
"head>\r\n                                <tbody>\r\n");


            
            #line 83 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                 foreach (var job in matchingJobs)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <tr class=\"js-jobs-list-row\">\r\n              " +
"                          <td>\r\n                                            <inp" +
"ut type=\"checkbox\" class=\"js-jobs-list-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 87 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                                                                                                 Write(job.Key);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                                        </td>\r\n                             " +
"           <td class=\"min-width\">\r\n                                            ");


            
            #line 90 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                       Write(Html.JobIdLink(job.Key));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </td>\r\n\r\n");


            
            #line 93 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                         if (job.Value == null)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <td colspan=\"3\">\r\n                   " +
"                             <em>");


            
            #line 96 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                               Write(Strings.Common_JobExpired);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n                                            </td>\r\n");


            
            #line 98 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <td class=\"word-break\">\r\n            " +
"                                    ");


            
            #line 102 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                           Write(Html.JobNameLink(job.Key, job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </td>\r\n");



WriteLiteral("                                            <td class=\"min-width align-right\">\r\n " +
"                                               ");


            
            #line 105 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                           Write(job.Value.State);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </td>\r\n");


            
            #line 107 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </tr>\r\n");


            
            #line 109 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                </tbody>\r\n                            </table>\r\n " +
"                       </div>\r\n\r\n                        ");


            
            #line 114 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                   Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");


            
            #line 116 "..\..\Dashboard\Pages\TagsSearchPage.cshtml"
                }
            }
        

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
